// <auto-generated />
namespace getadoc.Migrations.DataDb
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class diseasesChng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(diseasesChng));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091616146_diseasesChng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
